name: GitHub Slack Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types:
      - labeled

jobs:
  send-slack-notification:
    if: ${{ github.event.label.name == 'ide' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Issue labels updated\nIssue: <https://github.com/gradle/gradle/${{ github.event.issue.number }}|[gradle/gradle#${{ github.event.issue.number }}] ${{ github.event.issue.title }}>\nLabel: `${{ github.event.label.name }}`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Issue labels updated\nIssue: <https://github.com/gradle/gradle/${{ github.event.issue.number }}|[gradle/gradle#${{ github.event.issue.number }}] ${{ github.event.issue.title }}>\nLabel: `${{ github.event.label.name }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}