name: GitHub Slack Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types:
      - labeled

jobs:
  send-slack-notification:
    if: ${{ github.event.label.name == 'ide' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "gradle/gradle issue NUMBER has label ",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result 2"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}